[apps.http.servers.srv0]
  listen = [":443"]

  [[apps.http.servers.srv0.routes]]

    [[apps.http.servers.srv0.routes.handle]]
      handler = "vars"
      root = "{$CADDYWWWPATH}"

    [[apps.http.servers.srv0.routes.handle]]
      handler = "file_server"

[[apps.tls.automation.policies]]
  on_demand = true

  [[apps.tls.automation.policies.issuers]]
    module = "internal"

[apps.tls.automation.on_demand.rate_limit]
  interval = 1_000_000_000
  burst = 1

[apps.pki.certificate_authorities.local]
  install_trust = false
