[logging.logs.default]
  exclude = ["http.log.access.log0"]

[logging.logs.log0]
  include = ["http.log.access.log0"]

  [logging.logs.log0.writer]
    output = "stdout"

  [logging.logs.log0.encoder]
    format = "transform"
    template = """{common_log}"""

[apps.http.servers.srv0]
  listen = [":443"]

  [[apps.http.servers.srv0.routes]]
    terminal = true

    [[apps.http.servers.srv0.routes.match]]
      host = ["localhost"]

    [[apps.http.servers.srv0.routes.handle]]
      handler = "subroute"

      [[apps.http.servers.srv0.routes.handle.routes]]

        [[apps.http.servers.srv0.routes.handle.routes.handle]]
          handler = "vars"
          root = "{$CADDYWWWPATH:/var/www/html}"

        [[apps.http.servers.srv0.routes.handle.routes.handle]]
          handler = "file_server"

  [apps.http.servers.srv0.logs.logger_names]
    localhost = ["log0"]

[[apps.tls.automation.policies]]
  subjects = ["localhost"]

  [[apps.tls.automation.policies.issuers]]
    module = "internal"

[apps.pki.certificate_authorities.local]
  install_trust = false
