[logging.logs.default]
  exclude = ["http.log.access.log0"]

[logging.logs.log0]
  include = ["http.log.access.log0"]

  [logging.logs.log0.writer]
    output = "stdout"

  [logging.logs.log0.encoder]
    format = "transform"
    template = """{common_log}"""

[apps.http.servers.srv0]
  listen = [":443"]

  [[apps.http.servers.srv0.routes]]

    [[apps.http.servers.srv0.routes.handle]]
      handler = "vars"
      root = "{$CADDYWWWPATH}"

    [[apps.http.servers.srv0.routes.handle]]
      handler = "file_server"

  [apps.http.servers.srv0.logs]
    default_logger_name = "log0"

[[apps.tls.automation.policies]]
  on_demand = true

  [[apps.tls.automation.policies.issuers]]
    module = "internal"

[apps.tls.automation.on_demand.rate_limit]
  interval = 1_000_000_000
  burst = 1

[apps.pki.certificate_authorities.local]
  install_trust = false
