module caddy

require (
	github.com/caddyserver/caddy v1.0.3
	github.com/caddyserver/dnsproviders v0.3.0
	github.com/go-acme/lego v2.7.1
	// Explicitly define lego dependencies until the project migrates to Go modules.
	// (list generated by using: go mod init && go mod tidy)
	github.com/Azure/azure-sdk-for-go v31.0.0+incompatible
	github.com/Azure/go-autorest/autorest v0.5.0
	github.com/Azure/go-autorest/autorest/adal v0.2.0
	github.com/Azure/go-autorest/autorest/azure/auth v0.1.0
	github.com/Azure/go-autorest/autorest/to v0.2.0
	github.com/Azure/go-autorest/autorest/validation v0.1.0 // indirect
	github.com/BurntSushi/toml v0.3.1
	github.com/OpenDNS/vegadns2client v0.0.0-20180418235048-a3fa4a771d87
	github.com/akamai/AkamaiOPEN-edgegrid-golang v0.7.4
	github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190702055420-133cfe6c309b
	github.com/aws/aws-sdk-go v1.20.14
	github.com/cenkalti/backoff v2.1.1+incompatible
	github.com/cloudflare/cloudflare-go v0.9.2
	github.com/cpu/goacmedns v0.0.0-20180701200144-565ecf2a84df
	github.com/decker502/dnspod-go v0.2.0
	github.com/dnsimple/dnsimple-go v0.30.0
	github.com/exoscale/egoscale v0.18.1
	github.com/fatih/structs v1.1.0 // indirect
	github.com/go-errors/errors v1.0.1 // indirect
	github.com/go-ini/ini v1.38.2 // indirect
	github.com/google/uuid v0.0.0-20161128191214-064e2069ce9c // indirect
	github.com/gophercloud/gophercloud v0.0.0-20190204021847-a2b0ad6ce68c
	github.com/grpc-ecosystem/grpc-gateway v1.9.3 // indirect
	github.com/h2non/gock v0.0.0-00010101000000-000000000000 // indirect
	github.com/hashicorp/golang-lru v0.5.1 // indirect
	github.com/iij/doapi v0.0.0-20180911005243-8803795a9b7b
	github.com/kolo/xmlrpc v0.0.0-20181023172212-16bdd962781d // indirect
	github.com/labbsr0x/bindman-dns-webhook v1.0.0
	github.com/labbsr0x/goh v0.0.0-20190417202808-8b16b4848295 // indirect
	github.com/linode/linodego v0.10.0
	github.com/miekg/dns v1.1.15
	github.com/mitchellh/mapstructure v1.1.2 // indirect
	github.com/namedotcom/go v0.0.0-20180403034216-08470befbe04
	github.com/nrdcg/auroradns v1.0.0
	github.com/nrdcg/goinwx v0.6.0
	github.com/nrdcg/namesilo v0.2.0
	github.com/oracle/oci-go-sdk v5.13.0+incompatible
	github.com/ovh/go-ovh v0.0.0-20181109152953-ba5adb4cf014
	github.com/rainycape/memcache v0.0.0-20150622160815-1031fa0ce2f2
	github.com/sacloud/libsacloud v1.25.1
	github.com/stretchr/testify v1.3.0
	github.com/timewasted/linode v0.0.0-20160829202747-37e84520dcf7
	github.com/transip/gotransip v0.0.0-20190614113603-efb64632cab7
	github.com/urfave/cli v1.20.0
	github.com/vultr/govultr v0.1.4
	golang.org/x/crypto v0.0.0-20190418165655-df01cb2cc480
	golang.org/x/net v0.0.0-20190311183353-d8887717615a
	golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
	golang.org/x/sync v0.0.0-20190423024810-112230192c58 // indirect
	google.golang.org/api v0.3.2
	google.golang.org/genproto v0.0.0-20190404172233-64821d5d2107 // indirect
	gopkg.in/ns1/ns1-go.v2 v2.0.0-20190430170845-6c599e5e5790
	gopkg.in/square/go-jose.v2 v2.3.1
	gopkg.in/yaml.v2 v2.2.2 // indirect
)

replace github.com/h2non/gock => gopkg.in/h2non/gock.v1 v1.0.14
